/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/document/{citation}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_document__citation__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chunk/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chunk
         * @description Return the chunk and its neighbouring chunks.
         */
        get: operations["get_chunk_api_chunk__chunk_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_api_history__thread_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corpus/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Corpus Stats */
        get: operations["corpus_stats_api_corpus_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChunkContextResponse */
        ChunkContextResponse: {
            chunk: components["schemas"]["ChunkSlim"];
            prev_chunk?: components["schemas"]["ChunkSlim"] | null;
            next_chunk?: components["schemas"]["ChunkSlim"] | null;
            /** Document */
            document: {
                [key: string]: unknown;
            };
        };
        /** ChunkOut */
        ChunkOut: {
            /**
             * Chunk Id
             * @description e.g. 'pubmed:12345:0' or 'pmc:doc196:3'
             */
            chunk_id: string;
            /**
             * Citation
             * @description e.g. 'PMID:12345' or 'PMC:doc196'
             */
            citation: string;
            /**
             * Source
             * @description 'pubmed' or 'pmc'
             */
            source: string;
            /** Doc Id */
            doc_id: string;
            /** Title */
            title: string;
            /** Section */
            section?: string | null;
            /** Pmid */
            pmid?: string | null;
            /** Chunk Idx */
            chunk_idx: number;
            /** Total Chunks */
            total_chunks: number;
            /** Text */
            text: string;
            /** Score */
            score?: number | null;
            /** Highlight Ranges */
            highlight_ranges?: [
                number,
                number
            ][];
            /**
             * External Url
             * @default
             */
            external_url: string;
            /** Authors */
            authors?: string | null;
            /** Journal */
            journal?: string | null;
            /** Year */
            year?: number | null;
        };
        /** ChunkSlim */
        ChunkSlim: {
            /** Chunk Id */
            chunk_id: string;
            /** Text */
            text: string;
            /** Score */
            score?: number | null;
        };
        /** CorpusStats */
        CorpusStats: {
            /** Total Chunks */
            total_chunks: number;
            /** Pubmed Chunks */
            pubmed_chunks: number;
            /** Pmc Chunks */
            pmc_chunks: number;
            /** Collection */
            collection: string;
            /** Embedding Model */
            embedding_model: string;
        };
        /** DocumentChunkSlim */
        DocumentChunkSlim: {
            /** Chunk Id */
            chunk_id: string;
            /** Chunk Idx */
            chunk_idx: number;
            /** Section */
            section?: string | null;
            /** Text */
            text: string;
        };
        /** DocumentResponse */
        DocumentResponse: {
            /** Citation */
            citation: string;
            /** Source */
            source: string;
            /** Doc Id */
            doc_id: string;
            /** Title */
            title: string;
            /** Pmid */
            pmid: string | null;
            /** External Url */
            external_url: string;
            /** Total Chunks */
            total_chunks: number;
            /** Chunks */
            chunks: components["schemas"]["DocumentChunkSlim"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Qdrant */
            qdrant: string;
            /** Llm */
            llm: string;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Thread Id */
            thread_id: string;
            /** Turns */
            turns: components["schemas"]["HistoryTurn"][];
            /** Summary */
            summary: string;
        };
        /** HistoryTurn */
        HistoryTurn: {
            /** Query */
            query: string;
            /** Answer */
            answer: string;
            /** Citations */
            citations: string[];
            /** Timestamp */
            timestamp: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Pipeline */
            pipeline: string;
            /** Latency Ms */
            latency_ms: number;
            /** Chunks */
            chunks: components["schemas"]["ChunkOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
                k?: number;
                pipeline?: string;
                highlight?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_document__citation__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                citation: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chunk_api_chunk__chunk_id__get: {
        parameters: {
            query?: {
                context_window?: number;
            };
            header?: never;
            path: {
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkContextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_api_history__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    corpus_stats_api_corpus_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusStats"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    live_api_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
